### PR TITLE
allow overlays to show on different domains and subdomains

### LINKED ISSUE #110: allow overlays to show on different EDI domains
On the map view, if you select a different domain other than on the default 'Vulnerable on One or More Domains' and then add an overlay from 'Other data sources', it reverts the base map back to 'Vulnerable on One or More Domains'

Let's make whatever base map we were looking at stick when showing overlays

### PR DESCRIPTION
**Pull request by derekeder**
## Overview

Updates the logic in the map display to allow for the currently selected domain or subdomain to stay selected when adding circle overlays on top.

Creates two convenience functions `EDI.getDomainTitle` and `EDI.isDomain` to keep the code a bit more DRY and more reliable save state.

Closes #110 

### Demo

edi1

## Testing Instructions

Open up the map interface. Select different combinations of domains/subdomains and overlays. In all cases, the underlying choropleth map should not change. The legend titles and cutoffs for the domains and subdomains should also remain the same.

### CODE REVIEW

**Review by jeancochrane — COMMENTED** [review]
Works really well, and I like your refactor 👍 

One question I have about functionality: If you select a domain and then select an overlay, the UI will now maintain the correct domain. But if you then go back and switch to another domain, the UI will remove the selected overlay. Do you think that's fine given the spec we have?

**Comment by derekeder** [comment]
@jeancochrane good observation. I just pushed up a change that addresses it. The interactions were a bit tricky, but this is the behavior i think makes the most sense:

* when toggling between domains/subdomains, interactions are unchanged
* when selecting an overlay, the currently selected domain/subdomain remains highlighted
* if you then select another domain, the overlay becomes unselected since we remove it from the map as well
* it seemed a bit confusing to keep collapsing the domain panels whenever you switched, so they are now sticky as well when you open them

edi2

**Review by jeancochrane — APPROVED** [review]
This approach makes sense to me! Thanks for taking the time to think through the added element of domain-switching.

**Comment by derekeder** [comment]
😎

**Pull request merged**
